DPP-29 Open API implementation
Sphereon-Opensource/dpp-openapi pull request #1
Opened 2023-09-13 16:45 UTC by maikel-maas

2023-09-13 21:33 UTC, nklomp requested changes
Okay this was not meant to become a top level project (the ticket menations to make a multimodule in a subdir of the vdx-api), but leave that as is for now, given time constraints.

The ApiResponse object is not being used anywhere, so can be removed. Rest LGTM

2023-09-13 21:33 UTC, nklomp commented on assets/openapi/openapi.yaml
> +    ApiResponse:
This one can be removed

2023-09-14 07:37 UTC, maikel-maas commented on assets/openapi/openapi.yaml
> +    ApiResponse:
Removed

2023-09-14 09:21 UTC, nklomp approved these changes

2023-09-14 09:47 UTC, merged